[project]
name = ""
description = ""
origin = ""
author = ""
forked_from = ""
forked_at_step = 0

[source]
tool = "claude-code"
version = ""
model = ""

[collect]
sessions = [
    "0582c59e-e3bc-4ba5-8b29-608673767282",
    "4747d5fe-0ad5-4eb5-ae42-eb613d5adac4",
    "47964785-df04-497b-a043-7b90532c28cf",
    "7b42f3e3-6a97-427a-84a0-f83d2e1e83cf",
    "ad99caf6-19e6-4b2b-9669-ab5409d0a74b",
    "d771f496-21d3-45d1-a0c1-cca6dd892173",
    "10019629-b131-4a10-bce2-9cd4f24cc53d",
    "40352dc3-8a60-45c2-8711-478a60d8de00",
    "442532f1-097f-4011-b3b9-4baa0171f768",
    "6601ab67-e54b-4eb0-a2e6-ed82988ef27e",
    "83b27b1b-14da-4a34-900c-eacadece6903",
    "89c7a070-8308-4b51-92e4-d455fa285e35",
    "8fbb0ea0-f57e-41cc-b381-e4f43b0b008c",
    "b3e456d1-1fc3-4410-b73b-054bbf8419dd",
    "cf493284-facd-4d0a-adda-59c6da708888",
    "11e62204-658e-4977-bf52-5cf5d66d2a4e",
    "2e2a1023-84be-427b-b599-16414c59f010",
    "4ef3123f-5d8f-495e-b713-7b345d4956d8",
    "a764fbc0-71da-4461-8d48-9f43a82839cd",
    "bc3f990a-3e0c-4f56-9b19-d3a078c93c8e",
    "d04176aa-4382-494b-a3f5-1958c96c5bfd",
    "d25ac96f-50c0-4ae8-ac42-3547414f1804",
    "d7a5bd22-1c70-4607-84e5-5406dd513f1e",
    "f2402d3c-df61-4038-bdf7-9b32771a15d4",
    "fd1f9ac2-c500-4f06-b33c-c5a07b5fdcef",
]
